name: game
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.16.0
  flutter:
    sdk: flutter
  watt: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
