name: space_shooter_game
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flame: ^1.16.0
  flame_audio: ^2.10.0
  flutter:
    sdk: flutter
  nes_ui: ^0.18.0
  witt: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - fonts/
    - assets/images/joystick/
    - assets/images/misc/
    - assets/images/projectile/
    - assets/images/ship/
    - assets/images/
    - assets/audio/
